version: "3"

services:
  personal-website:
    container_name: personal-website
    build:
      context: ./personal-website
      dockerfile: dev.Dockerfile

    # Set environment variables directly in the docker-compose file
    environment:
      ENV_VARIABLE: ${ENV_VARIABLE}
      NEXT_PUBLIC_ENV_VARIABLE: ${NEXT_PUBLIC_ENV_VARIABLE}

    # Set environment variables based on the .env file
    env_file:
      - .env
    volumes:
      - ./src:/src
      - ./public:/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - network-1
      - db-network

networks:
  network-1:
    external: true
  db-network:
    external: true
